-- 기본 프로필(ddl-auto: create)에서 Hibernate가 테이블을 drop/create한 직후 실행된다.
-- 이 프로필의 역할은 "초기화"뿐이다. 스키마 제약과 데이터는 flyway-test 프로필이 담당한다.
--
-- flyway_schema_history는 엔티티가 아니라서 ddl-auto: create가 지우지 않는다.
-- 남겨두면 다음 flyway-test 실행에서 "V1~V5는 이미 적용됨"으로 판단해 시딩을 통째로 건너뛰고,
-- 테이블만 비어 있는 상태로 고정된다. 그래서 초기화 시점에 이력도 함께 지운다.
--
-- 주의: 이 파일에 여러 줄짜리 문장을 추가하려면 application.yaml의
-- hbm2ddl.import_files_sql_extractor 설정이 필요하다. 기본 파서는 한 줄을 한 문장으로 보고,
-- 실패해도 로그만 남기고 앱이 그대로 뜬다(halt_on_error 기본 false).
DROP TABLE IF EXISTS flyway_schema_history;
