-- 스키마 정의. 이 파일이 테이블 구조의 유일한 출처다.
--
-- 이전에는 Hibernate의 ddl-auto:create가 테이블을 만들고 Flyway가 데이터와 제약만 맡았다.
-- 그런데 Spring Boot는 Flyway를 EntityManagerFactory보다 먼저 실행하므로 한 번에 둘 다 켤 수
-- 없었고, 그래서 프로파일을 둘로 나눠 앱을 두 번 띄우는 우회로가 필요했다
-- (기본 프로파일로 스키마 생성 -> flyway-test로 시딩). 앱을 컨테이너에 올리면 이 춤이 더
-- 번거로워지므로, 스키마도 Flyway가 갖도록 바꾼다. 이제 기동 한 번으로 끝난다.
--
-- 이 DDL은 손으로 쓴 것이 아니라 Hibernate가 엔티티에서 생성한 것을 옮긴 것이다.
--   ./gradlew bootRun --args="--spring.jpa.properties.jakarta.persistence.schema-generation.scripts.action=create \
--                             --spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-target=schema.sql"
-- 엔티티를 바꾸면 위 명령으로 다시 뽑아 차이를 보고, 새 마이그레이션(V8, V9...)으로 추가한다.
-- 이 파일은 고치지 않는다 — 이미 적용된 DB에서 체크섬이 어긋난다.
--
-- 외래키 이름만 바꿨다. Hibernate가 붙이는 FK5vlh90qyii65ixwsbnafd55ud 같은 이름은
-- 제약 위반 로그를 읽을 수 없게 만든다. 이름을 바꿔도 JPA는 영향을 받지 않는다
-- (validate는 제약 이름을 보지 않는다). fk_feedback_user만 엔티티에 명시돼 있고,
-- V5가 ON DELETE SET NULL을 붙이려고 이 이름으로 DROP 후 재생성한다.


-- ─────────────────────────────────────────────────────────────
-- 콘텐츠 (JOINED 상속: content <- book / movie / music)
-- ─────────────────────────────────────────────────────────────

create table content (
    id              bigint generated by default as identity,
    dtype           varchar(31) not null,
    title           varchar(255),
    release_year    integer,
    s3object_key    varchar(255),
    image_extension varchar(255),
    primary key (id)
);

create table book (
    content_id bigint not null,
    author     TEXT,
    publisher  varchar(255),
    plot       TEXT,
    primary key (content_id)
);

create table movie (
    content_id   bigint not null,
    director     varchar(255) array,
    actor        varchar(255) array,
    running_time integer,
    plot         TEXT,
    primary key (content_id)
);

create table music (
    content_id bigint not null,
    artist     varchar(255) array,
    plot       TEXT,
    primary key (content_id)
);


-- ─────────────────────────────────────────────────────────────
-- 사용자
-- ─────────────────────────────────────────────────────────────

create table users (
    id          bigint generated by default as identity,
    login_id    varchar(255),
    pwd         varchar(255),
    email       varchar(255),
    nickname    varchar(255),
    birth_date  date,
    role        varchar(255) check (role       in ('USER','ADMIN','ANONYMOUS','MANAGER')),
    gender      varchar(255) check (gender     in ('MALE','FEMALE','OTHER')),
    login_type  varchar(255) check (login_type in ('LOCAL','OAUTH','ALL')),
    provider    varchar(255) check (provider   in ('GOOGLE','KAKAO','NAVER')),
    provider_id varchar(255),
    created_at  timestamp(6),
    updated_at  timestamp(6),
    deleted_at  timestamp(6),
    primary key (id),
    constraint uk_provider_and_id unique (provider, provider_id)
);

-- 식별 관계: users.id를 PK 겸 FK로 쓴다(@MapsId).
create table user_vector (
    user_id     bigint not null,
    user_vector real[],
    updated_at  timestamp(6),
    primary key (user_id)
);

create table user_refresh_tokens (
    id         bigint generated by default as identity,
    user_id    bigint not null,
    jti        varchar(36) not null unique,
    expires_at timestamp(6) not null,
    primary key (id)
);

create index idx_user_refresh_tokens_expires_at on user_refresh_tokens (expires_at);


-- ─────────────────────────────────────────────────────────────
-- 보드
-- ─────────────────────────────────────────────────────────────

create table board (
    id                bigint generated by default as identity,
    user_id           bigint,
    board_type        varchar(255) check (board_type in ('USER_CUSTOM','AI_RECOMMEND','PRE_MADE')),
    visibility        varchar(255) not null check (visibility in ('PUBLIC','PRIVATE')),
    title             varchar(255),
    content_signature varchar(160) not null,
    like_count        bigint,
    created_at        timestamp(6),
    deleted_at        timestamp(6),
    primary key (id)
);

create table board_item (
    id         bigint generated by default as identity,
    board_id   bigint,
    content_id bigint,
    slot_no    integer not null,
    primary key (id)
);

-- 한 사용자가 같은 보드에 두 번 피드백할 수 없다. 이 제약이 없으면 좋아요 연타로
-- board.like_count가 실제보다 부풀어 오른다.
create table board_feedback (
    id         bigint generated by default as identity,
    board_id   bigint,
    user_id    bigint,
    rating     varchar(255) check (rating in ('LIKE','DISLIKE')),
    created_at timestamp(6),
    primary key (id),
    constraint uk_board_feedback_board_user unique (board_id, user_id)
);


-- ─────────────────────────────────────────────────────────────
-- 로그
-- ─────────────────────────────────────────────────────────────

-- 사용자가 탈퇴해도 남아야 하므로 user_id에 FK를 걸지 않는다(엔티티도 raw id로 들고 있다).
create table system_log (
    id         bigint generated by default as identity,
    user_id    bigint,
    event_type varchar(255) check (event_type in ('CLICK_BOARD','CLICK_CONTENT','UPDATE_BOARD','LIKE_BOARD')),
    payload    jsonb,
    timestamp  timestamp(6),
    primary key (id)
);


-- ─────────────────────────────────────────────────────────────
-- 외래키
-- ─────────────────────────────────────────────────────────────

alter table book       add constraint fk_book_content     foreign key (content_id) references content;
alter table movie      add constraint fk_movie_content    foreign key (content_id) references content;
alter table music      add constraint fk_music_content    foreign key (content_id) references content;

alter table user_vector add constraint fk_user_vector_user foreign key (user_id) references users;

alter table board      add constraint fk_board_user       foreign key (user_id)    references users;
alter table board_item add constraint fk_board_item_board foreign key (board_id)   references board;
alter table board_item add constraint fk_board_item_content foreign key (content_id) references content;

alter table board_feedback add constraint fk_feedback_board foreign key (board_id) references board;
-- V5가 ON DELETE SET NULL을 붙이려고 이 이름으로 DROP 후 재생성한다. 이름을 바꾸지 말 것.
alter table board_feedback add constraint fk_feedback_user  foreign key (user_id)  references users;
