-- 콘텐츠 스키마 (JOINED 상속: content <- book / movie / music).
--
-- ── 마이그레이션 구성 (2026-09-26 정리) ─────────────────────────────────────
-- 개발 단계라 기존 마이그레이션(V0~V12)을 기능별로 다시 묶었다. 이전에는 한 파일에서 만든 것을
-- 다음 파일에서 지우고 다시 만드는 식(인덱스 교체, FK 재생성, 컬럼 추가)이 쌓여 있었는데,
-- 최종 모양만 남기고 처음부터 그 모양으로 만든다. 항상 빈 DB에서 시작한다(docker compose down -v).
--
--   V1  ContentSchema       콘텐츠 테이블
--   V2  UserSchema          사용자, 취향 벡터, 리프레시 토큰
--   V3  BoardSchema         보드, 보드 아이템, 좋아요 — 규칙과 조회 인덱스까지
--   V4  SystemLogSchema     로그
--   V5~V7 Seed*             콘텐츠 데이터 (Java 마이그레이션, seed 패키지)
--   V8  ContentTitleSearch  제목 검색 인덱스 — 데이터를 넣은 뒤에 만들어야 빠르다
--
-- ── 스키마를 바꿀 때 ──────────────────────────────────────────────────────
-- 테이블 정의는 Hibernate가 엔티티에서 생성한 DDL을 옮긴 것이다. 손으로 쓰면 엔티티와 어긋난다.
--   ./gradlew bootRun --args="--spring.jpa.properties.jakarta.persistence.schema-generation.scripts.action=create \
--                             --spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-target=schema.sql"
-- 엔티티를 바꾸면 위 명령으로 다시 뽑아 차이를 보고 해당 기능의 파일을 고친다(개발 단계).
-- 운영 DB가 생긴 뒤에는 적용된 파일을 고치면 체크섬이 어긋나므로 새 버전을 추가해야 한다.
--
-- 외래키 이름만 바꿨다. Hibernate가 붙이는 FK5vlh90qyii65ixwsbnafd55ud 같은 이름은
-- 제약 위반 로그를 읽을 수 없게 만든다. 이름을 바꿔도 JPA는 영향을 받지 않는다.

create table content (
    id              bigint generated by default as identity,
    dtype           varchar(31) not null,
    -- 원본 데이터셋의 id. book=asin, movie=imdbId, music=Spotify track id.
    -- AI 서버와 벡터 CSV가 콘텐츠를 가리키는 id다. Qdrant는 content.id로 저장하므로,
    -- 벡터를 적재하거나(ContentVectorLoader) AI 서버의 수정 요청을 반영하려면 이 값으로 content.id를 찾는다.
    -- 이 짝이 RDB에 남아 있어 Qdrant가 비워져도(볼륨 없음) CSV만으로 벡터를 다시 적재할 수 있다.
    source_key      varchar(255) not null,
    title           varchar(255),
    release_year    integer,
    s3object_key    varchar(255),
    image_extension varchar(255),
    primary key (id)
);

-- 유일성은 (dtype, source_key)로 건다. 키 체계가 도메인마다 달라 서로 겹치지 않는다는 보장이 없고,
-- 조회도 늘 도메인 하나로 좁혀서 한다. 원본 CSV의 중복(movie 593행, music 354행, 모든 필드가 같은 행)은
-- 시딩(V6, V7)이 넣기 전에 걸러내며, 이 인덱스가 그 규칙을 DB에서도 강제한다.
-- 시딩 전에 만들어 두어, 걸러내기가 빠지면 적재 단계에서 바로 실패하게 한다.
create unique index ux_content_source_key on content (dtype, source_key);

create table book (
    content_id bigint not null,
    author     TEXT,
    publisher  varchar(255),
    plot       TEXT,
    primary key (content_id)
);

create table movie (
    content_id   bigint not null,
    director     varchar(255) array,
    actor        varchar(255) array,
    running_time integer,
    plot         TEXT,
    primary key (content_id)
);

create table music (
    content_id bigint not null,
    artist     varchar(255) array,
    plot       TEXT,
    primary key (content_id)
);

alter table book  add constraint fk_book_content  foreign key (content_id) references content;
alter table movie add constraint fk_movie_content foreign key (content_id) references content;
alter table music add constraint fk_music_content foreign key (content_id) references content;
