-- 사용자 스키마: 사용자, 취향 벡터, 리프레시 토큰.

create table users (
    id          bigint generated by default as identity,
    login_id    varchar(255),
    pwd         varchar(255),
    email       varchar(255),
    nickname    varchar(255),
    birth_date  date,
    role        varchar(255) check (role       in ('USER','ADMIN','ANONYMOUS','MANAGER')),
    gender      varchar(255) check (gender     in ('MALE','FEMALE','OTHER')),
    login_type  varchar(255) check (login_type in ('LOCAL','OAUTH','ALL')),
    provider    varchar(255) check (provider   in ('GOOGLE','KAKAO','NAVER')),
    provider_id varchar(255),
    created_at  timestamp(6),
    updated_at  timestamp(6),
    deleted_at  timestamp(6),
    primary key (id),
    constraint uk_provider_and_id unique (provider, provider_id)
);

-- ── 조회 유니크 인덱스 ────────────────────────────────────────────────────
-- 없으면 로그인할 때마다 users 전체를 훑는다. 사용자 1,001명에서는 0.039ms라 눈에 띄지 않지만
-- 비용이 O(사용자 수)다. 100만 명이면 로그인 시도 한 번에 약 25,000블록(200MB)을 읽는다.
-- 게다가 이 경로는 로그인이 실패할 때도 돈다 — 인증 없이 외부에서 부를 수 있는 엔드포인트가
-- 풀스캔을 유발한다. 실측 25블록 -> 3블록.
--
-- UNIQUE인 이유: 앱이 이미 중복을 막는 값이라(existsByEmail, existsByNickname 등), 그 규칙을
-- DB도 강제한다. 조회를 빠르게 하는 것과 규칙을 강제하는 것을 인덱스 하나로 같이 얻는다.
--
-- 탈퇴한 사용자(deleted_at IS NOT NULL)의 값도 계속 점유한다. 부분 인덱스로 풀어주지 않는다 —
-- 앱은 이미 "탈퇴해도 아이디는 반납되지 않는다"로 동작한다. 여기서 바꾸면 정책 변경이 된다.
--
-- NULL은 막지 않는다. PostgreSQL의 UNIQUE는 NULL을 서로 다른 값으로 보므로(NULLS DISTINCT),
-- login_id가 없는 소셜 가입 계정이 여럿이어도 충돌하지 않는다.
create unique index uk_users_login_id on users (login_id);
create unique index uk_users_email    on users (email);
create unique index uk_users_nickname on users (nickname);

-- ── 취향 벡터 ────────────────────────────────────────────────────────────
-- 식별 관계: users.id를 PK 겸 FK로 쓴다(@MapsId). 가입 직후 콘텐츠를 고를 때 행이 생긴다.
--
--   user_vector          추천에 쓰는 벡터(한 칸). 좋아요가 바뀔 때마다 "좋아요한 보드들 +
--                        가입 때 고른 콘텐츠"로 처음부터 다시 계산한다.
--   initial_content_ids  가입 때 고른 콘텐츠 id(1~10개). 한 번 쓰고 바꾸지 않는다.
--
-- 좋아요는 board_feedback에, 콘텐츠 벡터는 Qdrant에 있어 언제든 다시 만들 수 있지만 가입 때
-- 고른 것은 여기 말고는 남는 곳이 없다. 평균 벡터가 아니라 id를 저장하는 이유: 콘텐츠 벡터가
-- 새 모델로 바뀌면 저장된 평균값만 옛 모델로 남아 두 모델의 벡터가 한 평균에 섞인다.
create table user_vector (
    user_id             bigint not null,
    user_vector         real[] not null,
    initial_content_ids bigint[] not null,
    updated_at          timestamp(6),
    primary key (user_id)
);

alter table user_vector add constraint fk_user_vector_user foreign key (user_id) references users;

-- ── 리프레시 토큰 ────────────────────────────────────────────────────────
create table user_refresh_tokens (
    id         bigint generated by default as identity,
    user_id    bigint not null,
    jti        varchar(36) not null unique,
    expires_at timestamp(6) not null,
    primary key (id)
);

create index idx_user_refresh_tokens_expires_at on user_refresh_tokens (expires_at);
