-- 로그 스키마.
--
-- 사용자가 탈퇴해도 남아야 하므로 user_id에 FK를 걸지 않는다(엔티티도 raw id로 들고 있다).

create table system_log (
    id         bigint generated by default as identity,
    user_id    bigint,
    event_type varchar(255) check (event_type in ('CLICK_BOARD','CLICK_CONTENT','UPDATE_BOARD','LIKE_BOARD')),
    payload    jsonb,
    timestamp  timestamp(6),
    primary key (id)
);
